name: 'URL Oracle'
description: 'Generate and verify cryptographically signed attestations for URL content monitoring'
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  command:
    description: 'Command to execute (generate_attestation, verify_attestation)'
    required: false
    default: ''
  url:
    description: 'URL to fetch and witness'
    required: false
    default: ''
  commit_sha:
    description: 'Commit SHA'
    required: false
    default: ''
  timestamp:
    description: 'Timestamp'
    required: false
    default: ''
  attestation_file:
    description: 'Attestation file name'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'

  args:
    - ${{ inputs.command != '' && inputs.command || '' }}
    - ${{ inputs.url != '' && '--url' || '' }}
    - ${{ inputs.url != '' && inputs.url || '' }}
    - ${{ inputs.commit_sha != '' && '--commit-sha' || '' }}
    - ${{ inputs.commit_sha != '' && inputs.commit_sha || '' }}
    - ${{ inputs.timestamp != '' && '--timestamp' || '' }}
    - ${{ inputs.timestamp != '' && inputs.timestamp || '' }}
    - ${{ inputs.attestation_file != '' && '--attestation-file' || '' }}
    - ${{ inputs.attestation_file != '' && inputs.attestation_file || '' }}
