name: Create Attestation

on:
  workflow_call:
    inputs:
      url:
        description: 'URL to fetch and witness'
        required: true
        type: string

jobs:
  create-attestation:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    
    steps:
    - name: Get current timestamp
      id: timestamp
      run: |
        echo "timestamp=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

    - name: Generate OpenPubkey attestation
      id: attestation
      uses: kipz/url-oracle@0087c73870c17f60fd1cbbd1010a01eedc141b41
      with:
        command: generate_attestation
        url: ${{ inputs.url }}
        commit_sha: 0087c73870c17f60fd1cbbd1010a01eedc141b41
        timestamp: ${{ steps.timestamp.outputs.timestamp }}
        attestation_file: "/github/workspace/attestation.json"

    - name: Upload attestation as artifact
      uses: actions/upload-artifact@v4
      with:
        name: attestation.json
        path: attestation.json
        retention-days: 30