name: Create Attestation

on:
  workflow_call:
    inputs:
      url:
        description: 'URL to fetch and witness'
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  create-attestation:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    
    steps:
    - name: Checkout repository at commit SHA
      uses: actions/checkout@v4
      with:
        repository: kipz/url-oracle
        token: ${{ secrets.token }}
    - name: Get commit SHA and timestamp
      id: metadata
      run: |
        echo "commit_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        echo "timestamp=$(git show -s --format=%cI HEAD)" >> $GITHUB_OUTPUT
    - name: Generate OpenPubkey attestation
      id: attestation
      run: |
        go run cmd/generate_attestation/main.go --url ${{ inputs.url }} --commit-sha ${{ steps.metadata.outputs.commit_sha }} --timestamp ${{ steps.metadata.outputs.timestamp }} --attestation-file attestation.json

    - name: Upload attestation as artifact
      uses: actions/upload-artifact@v4
      with:
        name: attestation.json
        path: attestation.json
        retention-days: 30