name: Create Attestation

on:
  workflow_call:
    inputs:
      url:
        description: 'URL to fetch and witness'
        required: true
        type: string

jobs:
  create-attestation:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      actions: read
    
    steps:
    - name: Checkout repository at current commit
      uses: actions/checkout@v4
      with:
        repository: kipz/url-oracle
    - name: Generate OpenPubkey attestation
      env:  
        CALLER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: attestation
      run: |
        go run cmd/generate_attestation/main.go --url ${{ inputs.url }} --attestation-file attestation.json --skip-previous

    - name: Upload attestation as artifact
      uses: actions/upload-artifact@v4
      with:
        name: attestation.json
        path: attestation.json
        retention-days: 30