name: Monitor OIDC JWKS

on:
  schedule:
    # Run every 2 hours
    - cron: '0 */2 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  monitor-jwks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "GitHub"
            url: "https://token.actions.githubusercontent.com/.well-known/jwks"
            description: "GitHub Actions OIDC provider for workload identity"
          - name: "Google"
            url: "https://accounts.google.com/.well-known/jwks"
            description: "Google OIDC provider for user authentication"
          - name: "Microsoft"
            url: "https://login.microsoftonline.com/common/discovery/v2.0/keys"
            description: "Microsoft Azure AD OIDC provider for authentication"
          - name: "GitLab"
            url: "https://gitlab.com/.well-known/jwks"
            description: "GitLab OIDC provider for user authentication"
    permissions:
      id-token: write
      contents: write
      actions: read
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set attestation filenames and workflow reference
      run: |
        PROVIDER_LOWER=$(echo "${{ matrix.name }}" | tr '[:upper:]' '[:lower:]')
        echo "ATTESTATION_FILE=attestation-${PROVIDER_LOWER}.json" >> $GITHUB_ENV
        echo "PREVIOUS_ATTESTATION_FILE=previous-attestation-${PROVIDER_LOWER}.json" >> $GITHUB_ENV
        # Construct job_workflow_ref in the format: owner/repo/.github/workflows/workflow-file@ref
        JOB_WORKFLOW_REF="${{ github.repository }}/.github/workflows/monitor-jwks.yml@${{ github.ref }}"
        echo "EXPECTED_WORKFLOW_REF=${JOB_WORKFLOW_REF}" >> $GITHUB_ENV
        echo "PROVIDER_NAME=${{ matrix.name }}" >> $GITHUB_ENV
        echo "PROVIDER_URL=${{ matrix.url }}" >> $GITHUB_ENV
    
    - name: Generate JWKS attestation for ${{ matrix.name }}
      env:
        CALLER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "🔍 Monitoring ${{ matrix.name }} JWKS endpoint: ${{ matrix.url }}"
        go run cmd/generate_attestation/main.go --url "${{ matrix.url }}" --attestation-file ${{ env.ATTESTATION_FILE }}
    
    - name: Upload ${{ matrix.name }} JWKS attestation as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ATTESTATION_FILE }}
        path: ${{ env.ATTESTATION_FILE }}
        retention-days: 30
