name: Monitor JWKS

on:
  schedule:
    # Run every 2 hours
    - cron: '0 */2 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  monitor-jwks:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      actions: read
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set attestation filenames
      run: |
        echo "ATTESTATION_FILE=attestation.json" >> $GITHUB_ENV
        echo "PREVIOUS_ATTESTATION_FILE=previous_attestation.json" >> $GITHUB_ENV
    
    - name: Generate JWKS attestation
      env:
        CALLER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        go run cmd/generate_attestation/main.go --url https://token.actions.githubusercontent.com/.well-known/jwks --attestation-file ${{ env.ATTESTATION_FILE }}
    
    - name: Upload JWKS attestation as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ATTESTATION_FILE }}
        path: ${{ env.ATTESTATION_FILE }}
        retention-days: 30
